### ISSUE TITLE
Super checklist

### ISSUE THREAD

**Issue by NovaLanceBrittany** [Kylebutcher/passpour#33]

**Comment by NovaLanceBrittany** [comment]
TODO:


Extra Tech / library: What are they:
- [ ] Bootstrap
- [ ] Web Socket .io (Joel) (new)
- [ ] Vanilla JS
- [ ] JQuery
- [ ] Mockaroo

NPM packages: What are they:
- [ ] Express
- [ ] Postgres
- [ ] Sequelize

Live Pages
- [ ] 1 person CSS
- [ ] Review all HTML Pages + CSS, record all that is left for each page 
- [ ] Review JS and what each page needs to do
- [ ] set up media queries for site responsiveness on mobile devices as well as desktop view.
- [ ] at least 1 page needs to be restricted by logged in users
- [ ] Landing page needs to have a log in and sign up form

JS to create elements
- [ ] bro everything needs to be created

API / Routes
- [ ] create API routes
- [ ] Each page should have a get
- [ ] User Page should have a post
- [ ] test with post man

Tests
- [ ] attempt to break the site
- [ ] make sure express & sequel are being read properly
- [ ] make sure the handle bars are applied to at least 1 page
- [ ] User table needs to have a hashed password

Presentation:
- [ ] Review Presentation
- [ ] assign roles for the Presentation
- [ ] assign the driver for the demo
- [ ] go through a dry run at least 1 time on Thursday

**Comment by J5imonson** [comment]
This list has been checked to reflect existing items on the kanban board
