### ISSUE TITLE
Daisy CheckList

### ISSUE THREAD

**Issue by daisyosebe** [Kylebutcher/passpour#43]
- [x] - [ ] Get rid of the table of Pours
- [x] - [ ] Get rid of the profile page and make the homepage the Profile page
- [x] HTML for landing/sign-in page
- [x] HTML for profile page
- [ ] CSS (all pages)
- [x] JS (bucketList) (append)
- [ ] put badges at the top of the page, then showcase, then bucket list
- [ ]  accolades append to a profile page
- [ ] Edit log-in to prompt for all info in the signup form
- [ ] password requirements 
- [x] handlebar all pages
